### ISSUE TITLE
hi jason

### ISSUE THREAD

**Issue by ksu-tech** [Mootbing/lake-projects#3]
did u get gh pro from you see vee tee ess?

**Comment by Mootbing** [comment]
no, I got it for free

**Comment by ksu-tech** [comment]
oh

**Comment by ksu-tech** [comment]
so can I get it?

**Comment by Mootbing** [comment]
no bceause you dont go to my schol

**Comment by ksu-tech** [comment]
ok but if i do

**Comment by Mootbing** [comment]
then u get it for free

**Comment by Mootbing** [comment]
github pro is not needed for me atleast anyways because I don't host websites or anythign like that, but I understand why you'd need it. Sucks cms doesn't have this

**Comment by ksu-tech** [comment]
yeah. is one of the perks being able to host multiple websites? is that why wisprtore uses it/

**Comment by Mootbing** [comment]
yea. I don't really need that perk because I don't code websites. but its always nice to flex the (PRO) badge

**Comment by wiisportsresort** [comment]
i dont use any of the gh pro features btw, hosting is through my own server and domain that i pay for

**Comment by ksu-tech** [comment]
oh, so you don't use the free website feature?

**Comment by wiisportsresort** [comment]
where
![image](https://user-images.githubusercontent.com/55799457/108068320-eb657200-702f-11eb-801d-2bfd7eb62c75.png)

**Comment by ksu-tech** [comment]
i was looking at it a while ago and it said somehting about having multiple websitse
